# Base image
FROM openjdk:21-jdk-slim

# Set working directory
WORKDIR /app

# Copy Gradle wrapper and other necessary files
COPY gradlew /app/
COPY gradle /app/gradle/
COPY build.gradle /app/
COPY settings.gradle /app/

#COPY common/build.gradle /app/common/
#COPY common/src /app/common/src

COPY api-gateway/build.gradle /app/api-gateway/
COPY api-gateway/src /app/api-gateway/src

# Ensure gradlew is executable
RUN chmod +x gradlew

# Build the application
RUN ./gradlew api-gateway:build -x test --stacktrace

# Check the build output directory
RUN ls -l api-gateway/build/libs/

# Copy the built JAR file to /app.jar
RUN cp api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar /app.jar

# Expose port
EXPOSE 8765

# Run the application
CMD ["java", "-jar", "/app.jar"]
