# Base image
FROM openjdk:21-jdk-slim

# Set working directory
WORKDIR /app

# Copy Gradle wrapper and other necessary files
COPY gradlew /app/
COPY gradle /app/gradle/
COPY build.gradle /app/
COPY settings.gradle /app/

COPY eureka-server/build.gradle /app/eureka-server/
COPY eureka-server/src /app/eureka-server/src

# Ensure gradlew is executable
RUN chmod +x gradlew

# Build the application
RUN ./gradlew eureka-server:build -x test --stacktrace

# Check the build output directory
RUN ls -l eureka-server/build/libs/

# Copy the built JAR file to /app.jar
RUN cp eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar /app.jar

# Expose port
EXPOSE 8761

# Run the application
CMD ["java", "-jar", "/app.jar"]
