FROM openjdk:21-jdk-slim

WORKDIR /app

# Copy Gradle wrapper and other necessary files
COPY gradlew /app/
COPY gradle /app/gradle/
COPY build.gradle /app/
COPY settings.gradle /app/

COPY common/build.gradle /app/common/
COPY common/src /app/common/src

COPY streaming-ad-service/build.gradle /app/streaming-ad-service/
COPY streaming-ad-service/src /app/streaming-ad-service/src

# Ensure gradlew is executable
RUN chmod +x gradlew

# Build the application
RUN ./gradlew streaming-ad-service:build -x test --stacktrace

# Check the build output directory
RUN ls -l streaming-ad-service/build/libs/

# Copy the built JAR file to /app.jar
RUN cp streaming-ad-service/build/libs/streaming-ad-service-0.0.1-SNAPSHOT.jar /app.jar

# Expose port
EXPOSE 8100

# Run the application
CMD ["java", "-jar", "/app.jar"]
