spring:
  application:
    name: streaming-ad-service

  profiles:
    active: local

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      profile: local
      name: streaming-service


server:
  port: 8000
